### ISSUE TITLE
Patrones entrega 0

### ISSUE THREAD

**Issue by matias19** [DDSGrupo14/DDS_G14_1C2018#7]
No entendí bien que patrón se podría aplicar en esta entrega.
Sería un composite con usuarios, y los domicilios como hojas?

**Comment by jalarosa** [comment]
Buenas,

Era para darles feedback de lo que subio Matias. 

No se si lo trabajaron en equipo esto, pero la idea es que puedan divirdirse el trabajo  y todos deberian tener aporte en el proyecto no solo Matias. Si tienen dificultad para divirse el trabajo diganme y yo les asigno tareas o veo como dividirles para que trabajen todos.
Con respecto al codigo les puedo decir lo siguiente. Resuelve el problema y les puede servir para llegar a solucionar el practico. Tiene desventajas como por ejemplo, es un esquema anemico, se puede caer en malas practicas como codigo duplicado y varios smell code y antipatterns. Es dificil de ver los patterns que se pueden aplicar porque deja de ser un esquema objetoso y esta orientado a desarrollar servicios.
Les paso un link para que vean una lista de antipatrones, es un sitio que tiene mucha informacion de patrones tambien con muy buenos ejemplos. Tomenla como referencia para pensar soluciones.

https://sourcemaking.com/antipatterns/software-development-antipatterns

​Para corregir esto, miren de nuevo el diagrama de clases que hicieron que estaba bastante bien.
Con el esquema que tienen con 3 metodos polimorficos resuelven lo pedido en la entrega 0.

Tienen el siguiente esquema

Usuario:
cantidadDispositivosPrendidos()
cantidadDispositivosApagados()
cantidadTotalDispositivos()

Domicilio:
cantidadDispositivosPrendidos()
cantidadDispositivosApagados()
cantidadTotalDispositivos()

Dispositivo:
cantidadDispositivosPrendidos()
cantidadDispositivosApagados()
cantidadTotalDispositivos()

Al usuario le piden la cantidadDispositivos (prendidos,apagados,total) este tiene los domicilios y le pide a cada uno de ellos
la cantidadDispositivos (prendidos,apagados,total) , luego el Domicilio tiene una lista de dispositivos donde nuevamente
cada dispositivo conoce su estado y responde 0 o 1 segun corresponda. Sumamos todo y tenemos el resultado final.

Como trabajo final piensen que patrones de diseno podemos llegar a necesitar en la solucion.
Les doy pistas: https://sourcemaking.com/design_patterns/structural_patterns
tienen objetos simples como el dispositivo y objetos compuestos como el usuario y el domicilio. A su vez como regla adicional
siempre que uso este pattern queda asociado un creational pattern. Podria ser un builder o un factoryMethod.
